# Generated by Django 6.0.4 on 2026-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=40)),
                ('description', models.CharField(db_column='description', max_length=40)),
                ('website', models.CharField(db_column='website', max_length=40)),
                ('phone', models.IntegerField(db_column='phone')),
                ('verified', models.BooleanField(db_column='verified')),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=40)),
                ('description', models.CharField(db_column='description', max_length=40)),
                ('salary_range', models.CharField(db_column='salary_range', max_length=40)),
                ('modality', models.CharField(db_column='modality', max_length=40)),
                ('category', models.CharField(db_column='category', max_length=40)),
                ('latitude', models.CharField(db_column='latitude', max_length=40)),
                ('longitude', models.CharField(db_column='longitude', max_length=40)),
                ('address', models.CharField(db_column='address', max_length=40)),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('created_at', models.DateField(db_column='created_at')),
            ],
            options={
                'db_table': 'jobpost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
